spring.application.name=tinta-core
spring.profiles.active=test
server.port=8081

# SWAGGER
springdoc.swagger-ui.path=/swagger-ui.html

spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin
spring.jms.template.receive-timeout=5000