spring.application.name=tinta-core
spring.profiles.active=mysql
server.port=8081

# SWAGGER
springdoc.swagger-ui.path=/swagger-ui.html

#spring.activemq.broker-url=tcp://localhost:61616
#spring.activemq.user=admin
#spring.activemq.password=admin
#spring.jms.template.receive-timeout=5000

# Docker
spring.activemq.broker-url=${SPRING_ACTIVEMQ_BROKER_URL:tcp://localhost:61616}
spring.activemq.user=admin
spring.activemq.password=admin

spring.jms.template.receive-timeout=5000

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
server.error.include-exception=true
logging.level.org.springframework.security=DEBUG